---
- name: C2RHEL
  hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Checa IP
    debug: 
      msg: "{{ ansible_hostname }}:{{ ansible_default_ipv4.address }}"
  - name: Checa OS
    debug:
      msg:
      - "ansible_distribution {{ hostvars[inventory_hostname].ansible_distribution }}"
      - "major version {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
      - "version {{ hostvars[inventory_hostname].ansible_distribution_version }}"
