---
- name: Ping Sample
  hosts: all
  connection: local
  tasks:
  - name: ping
    shell: ping -c 1 -w 2 8.8.8.8
    ignore_errors: true
    register: out
  
  - name: Run ls.sh and output "ls /"
      script: ls.sh
      register: out

  - debug: var=out.stdout_lines
