---
- name: Ping Sample
  hosts: all
  connection: local
  tasks:
  - name: ping
    ansible.netcommon.net_ping:
      dest: 192.168.0.94
    ignore_errors: true
    register: out
    debug: var=out.stdout_lines
